language: java
jdk:
  - oraclejdk8
  - openjdk8
# Using only Java 8 to compile the build because...
# 1) Java 6 destroys absolutely everything
# 2) Java 7 (openjdk) doesn't trust Gradle's certificate for whatever reason
# 3) It seems that Java 9 and ForgeGradle are having some little arguments
# Once the above reasons are fixed, we will resume building on those JDKs too
sudo: required
dist: trusty
addons:
  hostname: OpenMods-Host
before_install:
  - echo === SETTING ENVIRONMENT UP ===
  - echo Before install...
  - echo Updating submodules...
  - git submodule update --init --recursive
  - echo Setting up workspace...
  - chmod +x gradlew
  - ls -a -l -h --color
  - echo Downloading Gradle...
  - ./gradlew
  - ./gradlew -version
install:
  - echo Install...
  - ./gradlew setupCIWorkspace
  - ./gradlew assemble
before_script:
  - echo === CHECKING ===
  - echo Before script...
  - echo Printing dependencies...
  - ./gradlew dependencies
script:
  - echo Script...
  - ./gradlew check --info
after_success:
  - echo === BUILD SUCCESSFUL ===
  - echo Now building the artifacts
  - ./gradlew build
after_failure:
  - echo === BUILD FAILED ===
after_script:
  - echo After script...
  - echo === BUILD TERMINATED ===
notifications:
  email:
    recipients:
      - thesilkminer@outlook.com
    on_success: change
    on_failure: always
  slack:
    on_success: always
    on_failure: always
#Remove comments if allowed
#  irc:
#    channels:
#      - "irc.esper.net#OpenMods"
#    on_success: change
#    on_failure: always
#    template:
#      - "[Travis] New build: %{repository}#%{build_number} (%{branch} - %{commit} by %{author})"
#      - "[Travis] Message: %{message}"
#      - "[Travis] Change view : %{compare_url}"
#      - "[Travis] Build details : %{build_url}"
#    use_notice: true
